#!/usr/bin/env bash
# Build the Windows app: one folder the user can unzip and use.
#
#   ./packaging/windows/make-exes.sh                 # host arch (amd64 or arm64)
#   ./packaging/windows/make-exes.sh amd64           # explicit
#   ./packaging/windows/make-exes.sh amd64 arm64     # both
#
# Layout produced, matching Capri.app on macOS (GUI + engine, two processes):
#
#   Capri/Capri.exe              双击运行的就是它（GUI 子系统，无控制台窗口）
#   Capri/bin/Capri-host.exe     引擎，由 Capri.exe 拉起
#
# Environment:
#   VERSION  version stamp (default dev), same tag the release uses
#   OUT      output directory (default dist/windows)
#
# Cross-compiles fine from macOS or Linux: CGO_ENABLED=0 and no cgo in either
# binary. The manifest and the file icon are generated per architecture rather
# than committed as a .syso — a checked-in object file only covers the arch
# encoded in its name (which is how the arm64 build silently shipped without
# one), and it cannot be regenerated by a reader. Explorer takes Capri.exe's
# icon from that resource; the tray icon is the same file, read at runtime.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

VERSION="${VERSION:-dev}"
OUT="${OUT:-$ROOT/dist/windows}"

if [[ $# -gt 0 ]]; then
  ARCHES=("$@")
else
  case "$(uname -m)" in
    arm64 | aarch64) ARCHES=(arm64) ;;
    *) ARCHES=(amd64) ;;
  esac
fi

if [[ ! -f internal/server/web/dist/index.html ]]; then
  echo "missing internal/server/web/dist/index.html — copy capri-fe dist first" >&2
  exit 1
fi

MANIFEST="packaging/windows/tray.manifest"
rm -rf "$OUT"
mkdir -p "$OUT"

for arch in "${ARCHES[@]}"; do
  case "$arch" in
    amd64 | arm64) ;;
    *)
      echo "unknown arch $arch (want amd64 or arm64)" >&2
      exit 1
      ;;
  esac

  # Generate the resource object the Go linker picks up automatically for this
  # GOARCH, then remove it so it cannot be committed by accident. Capri.ico is
  # the file icon; the manifest is the execution level, DPI and controls.
  SYSO="cmd/capri-tray/rsrc_windows_${arch}.syso"
  go run github.com/akavel/rsrc -arch "$arch" \
    -manifest "$MANIFEST" \
    -ico cmd/capri-tray/assets/Capri.ico \
    -o "$SYSO"
  trap 'rm -f "$ROOT/cmd/capri-tray/rsrc_windows_"*.syso' EXIT

  dest="$OUT/$arch/Capri"
  mkdir -p "$dest/bin"

  # The engine goes in bin/ so the folder the user actually looks at holds one
  # obvious thing to run. It stays a console-subsystem binary: it logs to
  # stderr and its supervisor turns that into a file. -H=windowsgui here would
  # destroy the stream the tray is reading and buy nothing — nothing ever shows
  # its console window, because the tray starts it with CREATE_NO_WINDOW.
  echo "building bin/Capri-host.exe ($arch)"
  CGO_ENABLED=0 GOOS=windows GOARCH="$arch" \
    go build -trimpath \
    -ldflags "-s -w -X github.com/AgentsHarness/capri-host/internal/acp.Version=${VERSION}" \
    -o "$dest/bin/Capri-host.exe" ./cmd/capri-host

  # Capri.exe is the one that gets double-clicked, so it gets the GUI subsystem
  # (no console window) and the manifest above. Its source directory is still
  # cmd/capri-tray — that names the role, and the output name is set here.
  echo "building Capri.exe ($arch)"
  CGO_ENABLED=0 GOOS=windows GOARCH="$arch" \
    go build -trimpath \
    -ldflags "-s -w -H=windowsgui -X main.version=${VERSION}" \
    -o "$dest/Capri.exe" ./cmd/capri-tray

  rm -f "$SYSO"
  echo "built $dest"
done

echo "ok: $OUT"
